name: vina
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - rdkit>=2022.03.1
  - openbabel>=3.1.1
  - pymol-open-source>=2.5.0
  - vina>=1.2.3
  - numpy
  - scipy
  - jupyter
  - notebook
  - ipykernel
  - pip
  - pip:
    - autodock-vina
